# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program_mode.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 780)
        Form.setMinimumSize(QtCore.QSize(960, 780))
        Form.setStyleSheet("")
        self.python_l = QtWidgets.QLabel(Form)
        self.python_l.setGeometry(QtCore.QRect(0, 0, 960, 293))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(26)
        self.python_l.setFont(font)
        self.python_l.setStyleSheet("background-image: url(:/program_img/picture/python.png);")
        self.python_l.setText("")
        self.python_l.setObjectName("python_l")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 585, 960, 195))
        self.label_3.setStyleSheet("background-image: url(:/program_img/picture/math.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.python_btn = QtWidgets.QPushButton(Form)
        self.python_btn.setGeometry(QtCore.QRect(330, 10, 291, 91))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(48)
        self.python_btn.setFont(font)
        self.python_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.python_btn.setFlat(True)
        self.python_btn.setObjectName("python_btn")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(60, 100, 150, 90))
        self.pushButton.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 127);")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 180, 191, 90))
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color:rgb(0, 170, 127)")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 170, 150, 90))
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(28)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(85, 170, 255);")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(750, 90, 150, 90))
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(28)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(181, 255, 206);")
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.python_btn_2 = QtWidgets.QPushButton(Form)
        self.python_btn_2.setGeometry(QtCore.QRect(330, 300, 291, 91))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(48)
        self.python_btn_2.setFont(font)
        self.python_btn_2.setStyleSheet("color: rgb(255, 85, 0);")
        self.python_btn_2.setFlat(True)
        self.python_btn_2.setObjectName("python_btn_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 380, 150, 90))
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 170, 255);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(400, 410, 150, 90))
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_6.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(255, 0, 255);")
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 470, 150, 90))
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_7.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(244, 255, 222);")
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(590, 470, 150, 90))
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_8.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("color: rgb(255, 85, 255);")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(730, 380, 150, 90))
        self.pushButton_9.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_9.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color: rgb(85, 0, 255);")
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.python_btn_3 = QtWidgets.QPushButton(Form)
        self.python_btn_3.setGeometry(QtCore.QRect(330, 590, 291, 91))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(48)
        self.python_btn_3.setFont(font)
        self.python_btn_3.setStyleSheet("color: rgb(0, 255, 255);")
        self.python_btn_3.setFlat(True)
        self.python_btn_3.setObjectName("python_btn_3")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 690, 150, 90))
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_10.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: rgb(255, 85, 0);")
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(610, 690, 150, 90))
        self.pushButton_11.setMinimumSize(QtCore.QSize(150, 90))
        self.pushButton_11.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("color: rgb(255, 0, 127);")
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 290, 961, 301))
        self.label.setStyleSheet("background-image: url(:/program_img/picture/jiao.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.program_exit = QtWidgets.QPushButton(Form)
        self.program_exit.setGeometry(QtCore.QRect(30, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        self.program_exit.setFont(font)
        self.program_exit.setStyleSheet("QPushButton {\n"
"    border-radius:25px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:4px double rgb(85, 0, 127);\n"
"    background-color:rgb(0, 255, 255);\n"
"}\n"
"\n"
"")
        self.program_exit.setFlat(True)
        self.program_exit.setObjectName("program_exit")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(380, 100, 191, 90))
        self.pushButton_12.setMinimumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("color: rgb(255, 85, 0);")
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label.raise_()
        self.python_l.raise_()
        self.label_3.raise_()
        self.python_btn.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.python_btn_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.python_btn_3.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.program_exit.raise_()
        self.pushButton_12.raise_()

        self.retranslateUi(Form)
        self.program_exit.clicked.connect(Form.exit_program)
        self.pushButton_7.clicked.connect(Form.show_bat_pane)
        self.pushButton.clicked.connect(Form.show_torch)
        self.pushButton_4.clicked.connect(Form.show_pygame)
        self.pushButton_12.clicked.connect(Form.show_python)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.python_btn.setText(_translate("Form", "python库"))
        self.pushButton.setText(_translate("Form", "Pytorch"))
        self.pushButton_3.setText(_translate("Form", "Tensorflow"))
        self.pushButton_4.setText(_translate("Form", "Pygame"))
        self.pushButton_5.setText(_translate("Form", "PyQt5"))
        self.python_btn_2.setText(_translate("Form", "脚本命令"))
        self.pushButton_2.setText(_translate("Form", "Auto.js"))
        self.pushButton_6.setText(_translate("Form", "按键精灵"))
        self.pushButton_7.setText(_translate("Form", "BAT"))
        self.pushButton_8.setText(_translate("Form", "Shell"))
        self.pushButton_9.setText(_translate("Form", "Mysql"))
        self.python_btn_3.setText(_translate("Form", "数学工具"))
        self.pushButton_10.setText(_translate("Form", "Latex"))
        self.pushButton_11.setText(_translate("Form", "Matlab"))
        self.program_exit.setText(_translate("Form", "exit"))
        self.pushButton_12.setText(_translate("Form", "python"))
import program_images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
