# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'talk_solve_mode.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 780)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: rgb(255, 241, 181);")
        self.widget.setObjectName("widget")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:25px;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:4px double rgb(85, 0, 127);\n"
"    background-color:rgb(0, 255, 255);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(380, 20, 161, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(880, 30, 51, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius:25px;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:4px double rgb(85, 0, 127);\n"
"    background-color:rgb(0, 255, 255);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.widget_8.setObjectName("widget_8")
        self.label_2 = QtWidgets.QLabel(self.widget_8)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Qle = QtWidgets.QLineEdit(self.widget_8)
        self.Qle.setGeometry(QtCore.QRect(150, 10, 571, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.Qle.setFont(font)
        self.Qle.setStyleSheet("background-color: rgb(170, 208, 255);")
        self.Qle.setClearButtonEnabled(True)
        self.Qle.setObjectName("Qle")
        self.comboBox = QtWidgets.QComboBox(self.widget_8)
        self.comboBox.setGeometry(QtCore.QRect(730, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.widget_8)
        self.label_3.setGeometry(QtCore.QRect(60, 210, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser_anwser = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_anwser.setGeometry(QtCore.QRect(150, 210, 671, 221))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.textBrowser_anwser.setFont(font)
        self.textBrowser_anwser.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.textBrowser_anwser.setObjectName("textBrowser_anwser")
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        self.label_4.setGeometry(QtCore.QRect(60, 460, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_analysis = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_analysis.setGeometry(QtCore.QRect(150, 450, 671, 211))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.textBrowser_analysis.setFont(font)
        self.textBrowser_analysis.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.textBrowser_analysis.setObjectName("textBrowser_analysis")
        self.pushButton = QtWidgets.QPushButton(self.widget_8)
        self.pushButton.setGeometry(QtCore.QRect(850, 20, 91, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 240, 91, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 480, 91, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_7.setGeometry(QtCore.QRect(850, 570, 91, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser_sub = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_sub.setGeometry(QtCore.QRect(150, 80, 671, 121))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.textBrowser_sub.setFont(font)
        self.textBrowser_sub.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.textBrowser_sub.setObjectName("textBrowser_sub")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setGeometry(QtCore.QRect(60, 100, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(self.widget_8)
        self.radioButton.setGeometry(QtCore.QRect(880, 100, 30, 30))
        self.radioButton.setMinimumSize(QtCore.QSize(10, 10))
        self.radioButton.setSizeIncrement(QtCore.QSize(10, 10))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_8.setGeometry(QtCore.QRect(850, 140, 91, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.widget_8)
        self.horizontalLayout.addWidget(self.widget_5)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_2.setStretch(0, 7)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 13)

        self.retranslateUi(Form)
        self.pushButton_5.clicked.connect(Form.exit_talk_solve)
        self.pushButton_6.clicked.connect(Form.enter_datawrite)
        self.pushButton.clicked.connect(Form.search)
        self.pushButton_2.clicked.connect(Form.show_answer)
        self.pushButton_4.clicked.connect(Form.clear_answer)
        self.pushButton_3.clicked.connect(Form.show_analysis)
        self.pushButton_7.clicked.connect(Form.clear_analysis)
        self.pushButton_8.clicked.connect(Form.clear_sub)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_5.setText(_translate("Form", "exit"))
        self.label.setText(_translate("Form", "Answer"))
        self.pushButton_6.setText(_translate("Form", "into"))
        self.label_2.setText(_translate("Form", "问题："))
        self.comboBox.setItemText(0, _translate("Form", "family"))
        self.comboBox.setItemText(1, _translate("Form", "mood"))
        self.comboBox.setItemText(2, _translate("Form", "paper"))
        self.comboBox.setItemText(3, _translate("Form", "attraction"))
        self.comboBox.setItemText(4, _translate("Form", "juan"))
        self.comboBox.setItemText(5, _translate("Form", "life"))
        self.comboBox.setItemText(6, _translate("Form", "lab"))
        self.comboBox.setItemText(7, _translate("Form", "study"))
        self.comboBox.setItemText(8, _translate("Form", "test"))
        self.label_3.setText(_translate("Form", "答案："))
        self.label_4.setText(_translate("Form", "分析："))
        self.pushButton.setText(_translate("Form", "查找"))
        self.pushButton_2.setText(_translate("Form", "展示"))
        self.pushButton_3.setText(_translate("Form", "展示"))
        self.pushButton_4.setText(_translate("Form", "清空"))
        self.pushButton_7.setText(_translate("Form", "清空"))
        self.label_5.setText(_translate("Form", "备选："))
        self.pushButton_8.setText(_translate("Form", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
