# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'writing_mode.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 780)
        Form.setMinimumSize(QtCore.QSize(960, 780))
        Form.setMaximumSize(QtCore.QSize(960, 780))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(350, 20, 221, 91))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(48)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 40, 61, 61))
        font = QtGui.QFont()
        font.setFamily("华文宋体")
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius:25px;\n"
"    color: rgb(255, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:4px double rgb(85, 0, 127);\n"
"    background-color:rgb(0, 255, 255);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(36)
        self.widget_3.setFont(font)
        self.widget_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.widget_8.setObjectName("widget_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 40, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(26)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(170, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.widget_6.setObjectName("widget_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 40, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(26)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.widget_9.setObjectName("widget_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 40, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(26)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_4)
        self.widget_10.setStyleSheet("background-color: rgb(255, 85, 255);")
        self.widget_10.setObjectName("widget_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 50, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(26)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_4)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_3.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_4)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_3.addWidget(self.widget_12)
        self.horizontalLayout.addWidget(self.widget_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)

        self.retranslateUi(Form)
        self.pushButton_6.clicked.connect(Form.writing_exit)
        self.pushButton_2.clicked.connect(Form.paper_interpreter)
        self.pushButton_3.clicked.connect(Form.projection_document)
        self.pushButton_4.clicked.connect(Form.email_communication)
        self.pushButton_7.clicked.connect(Form.progress_report)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "写作"))
        self.pushButton_6.setText(_translate("Form", "exit"))
        self.pushButton_2.setText(_translate("Form", "论文解读"))
        self.pushButton_4.setText(_translate("Form", "邮件沟通"))
        self.pushButton_3.setText(_translate("Form", "项目文档"))
        self.pushButton_7.setText(_translate("Form", "进度汇报"))
import program_images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
