# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'write_database_mode.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(961, 780)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.widget.setObjectName("widget")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 50, 51, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:25px;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:4px double rgb(85, 0, 127);\n"
"    background-color:rgb(0, 255, 255);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(320, 40, 271, 71))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(570, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("background-color: rgb(230, 245, 225);")
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Qle = QtWidgets.QLineEdit(self.widget_2)
        self.Qle.setGeometry(QtCore.QRect(180, 150, 641, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.Qle.setFont(font)
        self.Qle.setStyleSheet("background-color: rgb(170, 208, 255);")
        self.Qle.setClearButtonEnabled(True)
        self.Qle.setObjectName("Qle")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(90, 290, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(90, 430, 71, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Asle = QtWidgets.QLineEdit(self.widget_2)
        self.Asle.setGeometry(QtCore.QRect(180, 290, 641, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.Asle.setFont(font)
        self.Asle.setStyleSheet("background-color: rgb(170, 208, 255);")
        self.Asle.setClearButtonEnabled(True)
        self.Asle.setObjectName("Asle")
        self.Ayle = QtWidgets.QLineEdit(self.widget_2)
        self.Ayle.setGeometry(QtCore.QRect(180, 430, 641, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.Ayle.setFont(font)
        self.Ayle.setStyleSheet("background-color: rgb(170, 208, 255);")
        self.Ayle.setClearButtonEnabled(True)
        self.Ayle.setObjectName("Ayle")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(400, 520, 161, 71))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(150, 40, 101, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setGeometry(QtCore.QRect(270, 40, 131, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(480, 40, 81, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.IDle = QtWidgets.QLineEdit(self.widget_2)
        self.IDle.setGeometry(QtCore.QRect(580, 40, 171, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.IDle.setFont(font)
        self.IDle.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.IDle.setObjectName("IDle")
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.submit)
        self.pushButton_5.clicked.connect(Form.exit_database)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_5.setText(_translate("Form", "exit"))
        self.label.setText(_translate("Form", "Database"))
        self.comboBox_2.setItemText(0, _translate("Form", "write"))
        self.comboBox_2.setItemText(1, _translate("Form", "fix"))
        self.comboBox_2.setItemText(2, _translate("Form", "delete"))
        self.label_2.setText(_translate("Form", "问题："))
        self.label_3.setText(_translate("Form", "答案："))
        self.label_4.setText(_translate("Form", "分析："))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.label_5.setText(_translate("Form", "数据表:"))
        self.comboBox.setItemText(0, _translate("Form", "test"))
        self.comboBox.setItemText(1, _translate("Form", "paper"))
        self.comboBox.setItemText(2, _translate("Form", "mood"))
        self.comboBox.setItemText(3, _translate("Form", "attraction"))
        self.comboBox.setItemText(4, _translate("Form", "family"))
        self.comboBox.setItemText(5, _translate("Form", "lab"))
        self.comboBox.setItemText(6, _translate("Form", "juan"))
        self.comboBox.setItemText(7, _translate("Form", "life"))
        self.comboBox.setItemText(8, _translate("Form", "study"))
        self.label_6.setText(_translate("Form", "ID号:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
