# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plan_split_mode.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 780)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 960, 780))
        self.widget.setStyleSheet("background-color: rgb(255, 247, 225);")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(240, 160, 81, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.event3_le = QtWidgets.QLineEdit(self.widget)
        self.event3_le.setGeometry(QtCore.QRect(340, 410, 481, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(20)
        self.event3_le.setFont(font)
        self.event3_le.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.event3_le.setClearButtonEnabled(True)
        self.event3_le.setObjectName("event3_le")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(440, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(240, 240, 91, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.event4_le = QtWidgets.QLineEdit(self.widget)
        self.event4_le.setGeometry(QtCore.QRect(340, 490, 481, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(20)
        self.event4_le.setFont(font)
        self.event4_le.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.event4_le.setClearButtonEnabled(True)
        self.event4_le.setObjectName("event4_le")
        self.type_le = QtWidgets.QLineEdit(self.widget)
        self.type_le.setGeometry(QtCore.QRect(730, 160, 91, 41))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(16)
        self.type_le.setFont(font)
        self.type_le.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.type_le.setClearButtonEnabled(True)
        self.type_le.setObjectName("type_le")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 50, 51, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:25px;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:4px double rgb(85, 0, 127);\n"
"    background-color:rgb(0, 255, 255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(470, 690, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.event5_le = QtWidgets.QLineEdit(self.widget)
        self.event5_le.setGeometry(QtCore.QRect(340, 580, 481, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(20)
        self.event5_le.setFont(font)
        self.event5_le.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.event5_le.setClearButtonEnabled(True)
        self.event5_le.setObjectName("event5_le")
        self.name_le = QtWidgets.QLineEdit(self.widget)
        self.name_le.setGeometry(QtCore.QRect(340, 160, 291, 41))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(16)
        self.name_le.setFont(font)
        self.name_le.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.name_le.setClearButtonEnabled(True)
        self.name_le.setObjectName("name_le")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(240, 580, 91, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.event2_le = QtWidgets.QLineEdit(self.widget)
        self.event2_le.setGeometry(QtCore.QRect(340, 320, 481, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(20)
        self.event2_le.setFont(font)
        self.event2_le.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.event2_le.setClearButtonEnabled(True)
        self.event2_le.setObjectName("event2_le")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(240, 490, 91, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(240, 410, 91, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(240, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(650, 160, 81, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.event1_le = QtWidgets.QLineEdit(self.widget)
        self.event1_le.setGeometry(QtCore.QRect(340, 240, 481, 51))
        font = QtGui.QFont()
        font.setFamily(".萍方-简")
        font.setPointSize(20)
        self.event1_le.setFont(font)
        self.event1_le.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.event1_le.setClearButtonEnabled(True)
        self.event1_le.setObjectName("event1_le")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.exit_plan_split)
        self.pushButton.clicked.connect(Form.submit_plan)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Name："))
        self.label_2.setText(_translate("Form", "计划分解"))
        self.label_4.setText(_translate("Form", "Event1："))
        self.pushButton_2.setText(_translate("Form", "exit"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.label_8.setText(_translate("Form", "Event5："))
        self.label_7.setText(_translate("Form", "Event4："))
        self.label_6.setText(_translate("Form", "Event3："))
        self.label_5.setText(_translate("Form", "Event2："))
        self.label.setText(_translate("Form", "Type："))
import program_images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
